name: Mirroring repo
on:
  push:
    branches:
      - test1_wdc2
jobs:
  mirroring:
    if: github.repository == 'multicharts/scanner-check'
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
        with:
          fetch-depth: 20
      - name: Preparing to mirror
        run: | 
          mkdir -p ~/.ssh && echo "${{ secrets.MIRROR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Mirroring to destination repo
        env:
          TARGET_REPO_URL: 'git@github.com:tradingview/scanner-check.git'
        run: | 
          git remote add mirror $TARGET_REPO_URL && git push --progress --prune --mirror mirror