name: Mirroring repo
on:
  push:
    branches:
      - sfo2
jobs:
  mirroring:
    if: github.repository == 'multicharts/scanner-check'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source repo"
        uses: actions/checkout@v3
        with:
          ref: "${{ github.ref_name }}"
          path: "source_repo"

      - name: "Checkout target repo"
        uses: actions/checkout@v3
        with:
          repository: 'tradingview/scanner-check'
          ref: "${{ github.ref_name }}"
          path: "target_repo"
          ssh-key: "${{ secrets.MIRROR_SSH_PRIVATE_KEY }}"

      - name: "Check branches source"
        run: |
          echo "Branch for mirroring: ${{ github.ref_name }}"
          cd source_repo
          [[ $(git branch| grep -v "*") -eq ${{ github.ref_name }} ]] && echo "Source repo has right branch" || exit 1
          
          cd ../target_repo
          [[ $(git branch| grep -v "*") -eq ${{ github.ref_name }} ]] && echo "Target repo has right branch" || exit 1
      - name: "Commit in target branch"
        run: |
          echo "Copy file from source repo in target repo folder."
          mkdir -p ~/.ssh && echo "${{ secrets.MIRROR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          
          rm -f target_repo/*
          yes | cp -rf source_repo/* target_repo
          cd target_repo && ls -la
          git config user.name robot_mirroring
          git config user.email robot_mirroring
          git add .
          git commit -m "mirroring from multicharts/scanner-check ref: ${{ github.ref_name }} commit_SHA: ${{ github.sha }}"
          git push
